### ISSUE TITLE
Writing database insertion code for new order/fill using flask-mongoengine

### ISSUE THREAD

**Issue by ypk4** [ypk4/Order-Management-Engine#1]
In run_flask_server.py file, appropriate database insertion/updation code for inserting new orders, fills etc is required to be completed in flask-mongoengine. Update Readme accrodingly when done.

**Comment by ioctls** [comment]
Used flask-pymongo instead. Used mlab to set up a MongoDB sever on AWS. ID/Password added to source. End point usage directly adds to the database now.

**Comment by ypk4** [comment]
Great work! :)
