### ISSUE TITLE
Modifying the JSON format of order details that will be returned to Order Entry

### ISSUE THREAD

**Issue by ypk4** [ypk4/Order-Management-Engine#10]
We have to modify type==5 if case inside order_entry() function so as to change the order details that we are sending the Order Entry group when user logs in. Code for old format is done, will have to modify it a bit.
![new format](https://user-images.githubusercontent.com/14861935/38467857-8f574e36-3b5b-11e8-8b9a-80a3182f8bc4.jpeg)
![old format](https://user-images.githubusercontent.com/14861935/38467862-95e3fe66-3b5b-11e8-8758-17f2079ae4bc.jpeg)

**Comment by ypk4** [comment]
The first image is New format and the second one is Old format

**Comment by MayurBatwal** [comment]
Format change done

**Comment by ypk4** [comment]
The new format according to which Mayur has done

[json format Order entry Get order details.txt](https://github.com/ypk4/Order-Management-Engine/files/1910133/json.format.Order.entry.Get.order.details.txt)

**Comment by ypk4** [comment]
Need to include 'order_qtydone' for each order in Order collection. It should be initialized to 0 whenever new order is created. When a new fill comes, its corresponding 'qtydone' field value should be added with the existing 'order_qtydone' value.
In 'if' case for "get order details" (type==5), return this 'order_qtydone' as 'QtyDone' to Order Entry for that order. Also, return QtyOpen as difference between 'total_qty' and 'order_qtydone'.
Note that "size" is nothing but "total_qty"

**Comment by ypk4** [comment]
** type == 4

**Comment by ypk4** [comment]
I have added QtyDone, QtyOpen, Symbol and ProductType fields. Yet, some fields are remaining.

**Comment by ypk4** [comment]
Added Client, PriceInstruction and Exchange fields while adding new order and in getting order details (type == 4)
