### ISSUE TITLE
Code for sending new order to Execution links and new fill to Trade management after inserting in DB

### ISSUE THREAD

**Issue by ypk4** [ypk4/Order-Management-Engine#2]
Writing code for sending new order in JSON format to Execution Links by calling their REST API url. This can be added in the order_entry() function in run_flask_server.py after inserting new order in database. Also, code for sending new fill in JSON format to Trade position management's REST API after inserting it in database.

**Comment by ioctls** [comment]
We don't have their REST APIs to do so rght now. We can't even try that till the three components are on the same network. We will need to do this in testing phase. They could use dummy data till then as we could provide them the templates.

**Comment by ypk4** [comment]
This is done using dummy REST APIs

**Comment by ypk4** [comment]
In commit 22 by @MayurBatwal
