### ISSUE TITLE
order_endpoint assumes every POST request is a new order to be inserted

### ISSUE THREAD

**Issue by ioctls** [ypk4/Order-Management-Engine#6]
GET request could be easily inferred to fetch data from DB. However we need to declare a standard data format to process these requests. The same interface will also be responsible for updating data in database such as the state of the order or its price. We could accommodate this within the standard request format or construct a new endpoint. Which option would be better?

**Comment by ypk4** [comment]
I suggest first option, as too many endpoints would be unnecessarily.

**Comment by ioctls** [comment]
If you need any help, just make another issue and assign me

**Comment by ypk4** [comment]
At most 10 ppl can be assigned to an issue

**Comment by ypk4** [comment]
Solved the issue in the latest commit. Please inform if any bug is found.
